name: Publish Package to NPM
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.0.0'

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package version
        run: |
          cd packages/chrome-extension
          npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bunx nx build @push-to/chrome-extension
        env:
          PUSHTO_CORE_URL: ${{ secrets.PUSHTO_CORE_URL }}

      - name: Publish to NPM
        run: cd packages/chrome-extension && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
